[Export]
slider_server_url="https://precomputed-staterequests--serene-pixie-862a4a.netlify.app/"
baked_state = false
baked_notebookfile = false
offer_binder = true
ignore_cache = [
    "index.jl",
]
create_index = false
exclude = [
    # these are in the repo but not used on the website
    "tools/*",
    "PlutoPages.jl",
]

[SliderServer]
port = 8080
host = "0.0.0.0"
exclude=[
    # these are in the repo but not used on the website
    "tools/*",
    "PlutoPages.jl",
    
    # notebooks not interactive
]
